/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KimosasraVar;
import controller.NemSzamFormatum;
import controller.NincsAdat;
import controller.VeszelyesenTele;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Hordo;

/**
 *
 * @author Gábor
 */
public class ablak1 extends javax.swing.JFrame {

    /**
     * Creates new form ablak1
     */
    public ablak1() {
        initComponents();
        initOwnComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hibaTabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        elerhetoUrmertekek = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        sorszamBeiro = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        valaszLiter = new javax.swing.JLabel();
        valaszSzazalek = new javax.swing.JLabel();
        hibaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borospince");

        hibaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(hibaTabla);

        jLabel3.setText("Űrmértékek: ");

        elerhetoUrmertekek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        elerhetoUrmertekek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elerhetoUrmertekekActionPerformed(evt);
            }
        });

        jLabel1.setText("Sorszám");

        sorszamBeiro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sorszamBeiroStateChanged(evt);
            }
        });

        jLabel2.setText("A hordó tartalma:");

        valaszLiter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valaszLiter.setText("0 liter");
        valaszLiter.setToolTipText("");

        valaszSzazalek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valaszSzazalek.setText("0 %");

        hibaLabel.setForeground(new java.awt.Color(204, 0, 51));
        hibaLabel.setText(" ");
        hibaLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valaszLiter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(valaszSzazalek, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sorszamBeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(hibaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(elerhetoUrmertekek, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 42, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(elerhetoUrmertekek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sorszamBeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hibaLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszLiter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valaszSzazalek)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Helyes adatok");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Hibás adatok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initOwnComponents(){
        this.joHordok = beolvaso("src/model/hordok.txt");
        
        urmertekFeltolto(this.joHordok);
        hibaTablaFeltolto(this.joHordok);
    }
    
    public void hibaTablaFeltolto(ArrayList<Hordo> hordok){
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"űrmérték", "adat", "hiba"});
        for (Hordo hordo : hordok) {
            for (int i = 0; i < hordo.getHibasAdatok().size(); i++) {
                model.addRow(new String[]{hordo.getUrmertek()+"", hordo.getHibasAdatok().get(i), hordo.getHibaTipusok().get(i)});
            }
        }        
        this.hibaTabla.setModel(model);        
    }
    
    public void urmertekFeltolto(ArrayList<Hordo> hordok){
        this.elerhetoUrmertekek.removeAllItems();
        this.elerhetoUrmertekek.addItem("Válasszon!");
        for (Hordo hordo : hordok) {
            if(hordo.getHordok().size()>0)
                this.elerhetoUrmertekek.addItem(hordo.getUrmertek()+" liter");
        }
    }
    
    public ArrayList<Hordo> beolvaso(String file){
        ArrayList<Hordo> list = new ArrayList<>();
        RandomAccessFile be;
        try {
            be = new RandomAccessFile(file, "r");
            while(be.getFilePointer()<be.length()){
                list.add(new Hordo(be.readLine()));
            }
            be.close();
        } catch (IOException e) {
            System.out.println("Hiba: "+e.getMessage());
        }     
        return list;
    }
    

    
    private void sorszamBeiroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sorszamBeiroStateChanged
        if(this.elerhetoUrmertekek.getSelectedIndex()>0){
            int sorszam = Integer.parseInt(this.sorszamBeiro.getValue().toString());
            if(sorszam<1){
                this.sorszamBeiro.setValue(1);
            }
            if(sorszam<this.minIndex){
                this.hibaLabel.setText("Tartományon kívüli érték");
            }
            else if(sorszam>this.maxIndex){
                this.hibaLabel.setText("Tartományon kívüli érték");
            }
            else {        
                this.hibaLabel.setText(" ");
                this.valaszLiter.setText(hordo.getHordok().get(sorszam-1)+" l");
                this.valaszSzazalek.setText(String.format("%.2f", hordo.getToltottsegSzazalek().get(sorszam-1))+" %");
            }
            
        }
    }//GEN-LAST:event_sorszamBeiroStateChanged

    private void elerhetoUrmertekekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elerhetoUrmertekekActionPerformed
        this.minIndex=0;
        this.maxIndex=0;
        this.valaszLiter.setText("");
        this.valaszSzazalek.setText("");
        this.hibaLabel.setText(" ");
        int index = this.elerhetoUrmertekek.getSelectedIndex();
        if(index>0) {
            this.hordo = this.joHordok.get(index-1);
            if(hordo.getHordok().size()>0){
                this.minIndex=1;
                this.maxIndex=hordo.getHordok().size();
            }
        }
    }//GEN-LAST:event_elerhetoUrmertekekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ablak1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ablak1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ablak1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ablak1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ablak1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> elerhetoUrmertekek;
    private javax.swing.JLabel hibaLabel;
    private javax.swing.JTable hibaTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sorszamBeiro;
    private javax.swing.JLabel valaszLiter;
    private javax.swing.JLabel valaszSzazalek;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Hordo> joHordok;
    private int minIndex;
    private int maxIndex;
    private Hordo hordo;


}
